package packetmappings

func init482() {
	mapping := NewMapping()

	// handshaking
	mapping.Set(false, StateHandshake, 0, HandshakingServerHandshake)

	// status
	mapping.Set(true, StateStatus, 0, StatusClientResponse)
	mapping.Set(true, StateStatus, 1, StatusClientPong)

	mapping.Set(false, StateStatus, 0, StatusServerRequest)
	mapping.Set(false, StateStatus, 1, StatusServerPing)

	// login
	mapping.Set(true, StateLogin, 0, LoginClientDisconnect)
	mapping.Set(true, StateLogin, 1, LoginClientEncryptionRequest)
	mapping.Set(true, StateLogin, 2, LoginClientLoginSuccess)
	mapping.Set(true, StateLogin, 3, LoginClientSetCompression)
	mapping.Set(true, StateLogin, 4, LoginClientLoginPluginRequest)

	mapping.Set(false, StateLogin, 0, LoginServerLoginStart)
	mapping.Set(false, StateLogin, 1, LoginServerEncryptionResponse)
	mapping.Set(false, StateLogin, 2, LoginServerLoginPluginResponse)

	// play
	mapping.Set(true, StatePlay, 0x00, PlayClientSpawnObject)
	mapping.Set(true, StatePlay, 0x01, PlayClientSpawnExperienceOrb)
	mapping.Set(true, StatePlay, 0x02, PlayClientSpawnGlobalEntity)
	mapping.Set(true, StatePlay, 0x03, PlayClientSpawnMob)
	mapping.Set(true, StatePlay, 0x04, PlayClientSpawnPainting)
	mapping.Set(true, StatePlay, 0x05, PlayClientSpawnPlayer)
	mapping.Set(true, StatePlay, 0x06, PlayClientAnimation)
	mapping.Set(true, StatePlay, 0x07, PlayClientStatistics)
	mapping.Set(true, StatePlay, 0x08, PlayClientBlockBreakAnimation)
	mapping.Set(true, StatePlay, 0x09, PlayClientUpdateBlockEntity)
	mapping.Set(true, StatePlay, 0x0A, PlayClientBlockAction)
	mapping.Set(true, StatePlay, 0x0B, PlayClientBlockChange)
	mapping.Set(true, StatePlay, 0x0C, PlayClientBossBar)
	mapping.Set(true, StatePlay, 0x0D, PlayClientServerDifficulty)
	mapping.Set(true, StatePlay, 0x0E, PlayClientChatMessage)
	mapping.Set(true, StatePlay, 0x0F, PlayClientMultiBlockChange)

	mapping.Set(true, StatePlay, 0x10, PlayClientTabComplete)
	mapping.Set(true, StatePlay, 0x11, PlayClientDeclareCommands)
	mapping.Set(true, StatePlay, 0x12, PlayClientConfirmTransaction)
	mapping.Set(true, StatePlay, 0x13, PlayClientCloseWindow)
	mapping.Set(true, StatePlay, 0x14, PlayClientOpenWindow)
	mapping.Set(true, StatePlay, 0x15, PlayClientWindowItems)
	mapping.Set(true, StatePlay, 0x16, PlayClientWindowProperty)
	mapping.Set(true, StatePlay, 0x17, PlayClientSetSlot)
	mapping.Set(true, StatePlay, 0x18, PlayClientSetCooldown)
	mapping.Set(true, StatePlay, 0x19, PlayClientPluginMessage)
	mapping.Set(true, StatePlay, 0x1A, PlayClientNamedSoundEffect)
	mapping.Set(true, StatePlay, 0x1B, PlayClientDisconnect)
	mapping.Set(true, StatePlay, 0x1C, PlayClientEntityStatus)
	mapping.Set(true, StatePlay, 0x1D, PlayClientNBTQueryResponse)
	mapping.Set(true, StatePlay, 0x1E, PlayClientExplosion)
	mapping.Set(true, StatePlay, 0x1F, PlayClientUnloadChunk)

	mapping.Set(true, StatePlay, 0x20, PlayClientChangeGameState)
	mapping.Set(true, StatePlay, 0x21, PlayClientKeepAlive)
	mapping.Set(true, StatePlay, 0x22, PlayClientChunkData)
	mapping.Set(true, StatePlay, 0x23, PlayClientEffect)
	mapping.Set(true, StatePlay, 0x24, PlayClientParticle)
	mapping.Set(true, StatePlay, 0x25, PlayClientJoinGame)
	mapping.Set(true, StatePlay, 0x26, PlayClientMapData)
	mapping.Set(true, StatePlay, 0x27, PlayClientEntity)
	mapping.Set(true, StatePlay, 0x28, PlayClientEntityRelativeMove)
	mapping.Set(true, StatePlay, 0x29, PlayClientEntityLookAndRelativeMove)
	mapping.Set(true, StatePlay, 0x2A, PlayClientEntityLook)
	mapping.Set(true, StatePlay, 0x2B, PlayClientVehicleMove)
	mapping.Set(true, StatePlay, 0x2C, PlayClientOpenSignEditor)
	mapping.Set(true, StatePlay, 0x2D, PlayClientCraftRecipeResponse)
	mapping.Set(true, StatePlay, 0x2E, PlayClientPlayerAbilities)
	mapping.Set(true, StatePlay, 0x2F, PlayClientCombatEvent)

	mapping.Set(true, StatePlay, 0x30, PlayClientPlayerInfo)
	mapping.Set(true, StatePlay, 0x31, PlayClientFacePlayer)
	mapping.Set(true, StatePlay, 0x32, PlayClientPlayerPositionAndLook)
	mapping.Set(true, StatePlay, 0x33, PlayClientUseBed)
	mapping.Set(true, StatePlay, 0x34, PlayClientUnlockRecipes)
	mapping.Set(true, StatePlay, 0x35, PlayClientDestroyEntities)
	mapping.Set(true, StatePlay, 0x36, PlayClientRemoveEntityEffect)
	mapping.Set(true, StatePlay, 0x37, PlayClientResourcePackSend)
	mapping.Set(true, StatePlay, 0x38, PlayClientRespawn)
	mapping.Set(true, StatePlay, 0x39, PlayClientEntityHeadLook)
	mapping.Set(true, StatePlay, 0x3A, PlayClientSelectAdvancementTab)
	mapping.Set(true, StatePlay, 0x3B, PlayClientWorldBorder)
	mapping.Set(true, StatePlay, 0x3C, PlayClientCamera)
	mapping.Set(true, StatePlay, 0x3D, PlayClientHeldItemChange)
	mapping.Set(true, StatePlay, 0x3E, PlayClientDisplayScoreboard)
	mapping.Set(true, StatePlay, 0x3F, PlayClientEntityMetadata)

	mapping.Set(true, StatePlay, 0x40, PlayClientAttachEntity)
	mapping.Set(true, StatePlay, 0x41, PlayClientEntityVelocity)
	mapping.Set(true, StatePlay, 0x42, PlayClientEntityEquipment)
	mapping.Set(true, StatePlay, 0x43, PlayClientSetExperience)
	mapping.Set(true, StatePlay, 0x44, PlayClientUpdateHealth)
	mapping.Set(true, StatePlay, 0x45, PlayClientScoreboardObjective)
	mapping.Set(true, StatePlay, 0x46, PlayClientSetPassengers)
	mapping.Set(true, StatePlay, 0x47, PlayClientTeams)
	mapping.Set(true, StatePlay, 0x48, PlayClientUpdateScore)
	mapping.Set(true, StatePlay, 0x49, PlayClientSpawnPosition)
	mapping.Set(true, StatePlay, 0x4A, PlayClientTimeUpdate)
	mapping.Set(true, StatePlay, 0x4B, PlayClientTitle)
	mapping.Set(true, StatePlay, 0x4C, PlayClientStopSound)
	mapping.Set(true, StatePlay, 0x4D, PlayClientSoundEffect)
	mapping.Set(true, StatePlay, 0x4E, PlayClientPlayerListHeaderAndFooter)
	mapping.Set(true, StatePlay, 0x4F, PlayClientCollectItem)

	mapping.Set(true, StatePlay, 0x50, PlayClientEntityTeleport)
	mapping.Set(true, StatePlay, 0x51, PlayClientAdvancements)
	mapping.Set(true, StatePlay, 0x52, PlayClientEntityProperties)
	mapping.Set(true, StatePlay, 0x53, PlayClientEntityEffect)
	mapping.Set(true, StatePlay, 0x54, PlayClientDeclareRecipes)
	mapping.Set(true, StatePlay, 0x55, PlayClientTags)

	// serverbound
	mapping.Set(false, StatePlay, 0x00, PlayServerTeleportConfirm)
	mapping.Set(false, StatePlay, 0x01, PlayServerQueryBlockNBT)
	mapping.Set(false, StatePlay, 0x02, PlayServerChatMessage)
	mapping.Set(false, StatePlay, 0x03, PlayServerClientStatus)
	mapping.Set(false, StatePlay, 0x04, PlayServerClientSettings)
	mapping.Set(false, StatePlay, 0x05, PlayServerTabComplete)
	mapping.Set(false, StatePlay, 0x06, PlayServerConfirmTransaction)
	mapping.Set(false, StatePlay, 0x07, PlayServerEnchantItem)
	mapping.Set(false, StatePlay, 0x08, PlayServerClickWindow)
	mapping.Set(false, StatePlay, 0x09, PlayServerCloseWindow)
	mapping.Set(false, StatePlay, 0x0A, PlayServerPluginMessage)
	mapping.Set(false, StatePlay, 0x0B, PlayServerEditBook)
	mapping.Set(false, StatePlay, 0x0C, PlayServerQueryEntityNBT)
	mapping.Set(false, StatePlay, 0x0D, PlayServerUseEntity)
	mapping.Set(false, StatePlay, 0x0E, PlayServerKeepAlive)
	mapping.Set(false, StatePlay, 0x0F, PlayServerPlayer)

	mapping.Set(false, StatePlay, 0x10, PlayServerPlayerPosition)
	mapping.Set(false, StatePlay, 0x11, PlayServerPlayerPositionAndLook)
	mapping.Set(false, StatePlay, 0x12, PlayServerPlayerLook)
	mapping.Set(false, StatePlay, 0x13, PlayServerVehicleMove)
	mapping.Set(false, StatePlay, 0x14, PlayServerSteerBoat)
	mapping.Set(false, StatePlay, 0x15, PlayServerPickItem)
	mapping.Set(false, StatePlay, 0x16, PlayServerCraftRecipeRequest)
	mapping.Set(false, StatePlay, 0x17, PlayServerPlayerAbilities)
	mapping.Set(false, StatePlay, 0x18, PlayServerPlayerDigging)
	mapping.Set(false, StatePlay, 0x19, PlayServerEntityAction)
	mapping.Set(false, StatePlay, 0x1A, PlayServerSteerVehicle)
	mapping.Set(false, StatePlay, 0x1B, PlayServerRecipeBookData)
	mapping.Set(false, StatePlay, 0x1C, PlayServerNameItem)
	mapping.Set(false, StatePlay, 0x1D, PlayServerResourcePackStatus)
	mapping.Set(false, StatePlay, 0x1E, PlayServerAdvancementTab)
	mapping.Set(false, StatePlay, 0x1F, PlayServerSelectTrade)

	mapping.Set(false, StatePlay, 0x20, PlayServerSetBeaconEffect)
	mapping.Set(false, StatePlay, 0x21, PlayServerHeldItemChange)
	mapping.Set(false, StatePlay, 0x22, PlayServerUpdateCommandBlock)
	mapping.Set(false, StatePlay, 0x23, PlayServerUpdateCommandBlockMinecart)
	mapping.Set(false, StatePlay, 0x24, PlayServerCreativeInventoryAction)
	mapping.Set(false, StatePlay, 0x25, PlayServerUpdateStructureBlock)
	mapping.Set(false, StatePlay, 0x26, PlayServerUpdateSign)
	mapping.Set(false, StatePlay, 0x27, PlayServerAnimation)
	mapping.Set(false, StatePlay, 0x28, PlayServerSpectate)
	mapping.Set(false, StatePlay, 0x29, PlayServerPlayerBlockPlacement)
	mapping.Set(false, StatePlay, 0x2A, PlayServerUseItem)

	mapping.finish(482)
}
