package packetmappings

func init482() {
	mapping := NewMapping()

	// handshaking
	mapping.Set(false, StateHandshake, 0, HandshakingServerHandshake)

	// status
	mapping.Set(true, StateStatus, 0, StatusClientResponse)
	mapping.Set(true, StateStatus, 1, StatusClientPong)

	mapping.Set(false, StateStatus, 0, StatusServerRequest)
	mapping.Set(false, StateStatus, 1, StatusServerPing)

	// login
	mapping.Set(true, StateLogin, 0, LoginClientDisconnect)
	mapping.Set(true, StateLogin, 1, LoginClientEncryptionRequest)
	mapping.Set(true, StateLogin, 2, LoginClientLoginSuccess)
	mapping.Set(true, StateLogin, 3, LoginClientSetCompression)
	mapping.Set(true, StateLogin, 4, LoginClientLoginPluginRequest)

	mapping.Set(false, StateLogin, 0, LoginServerLoginStart)
	mapping.Set(false, StateLogin, 1, LoginServerEncryptionResponse)
	mapping.Set(false, StateLogin, 2, LoginServerLoginPluginResponse)

	// play
	mapping.Set(true, StatePlay, 0x00, PlayClientSpawnObject)
	mapping.Set(true, StatePlay, 0x01, PlayClientSpawnExperienceOrb)
	mapping.Set(true, StatePlay, 0x02, PlayClientSpawnGlobalEntity)
	mapping.Set(true, StatePlay, 0x03, PlayClientSpawnMob)
	mapping.Set(true, StatePlay, 0x04, PlayClientSpawnPainting)
	mapping.Set(true, StatePlay, 0x05, PlayClientSpawnPlayer)
	mapping.Set(true, StatePlay, 0x06, PlayClientAnimation)
	mapping.Set(true, StatePlay, 0x07, PlayClientStatistics)
	mapping.Set(true, StatePlay, 0x08, PlayClientBlockBreakAnimation)
	mapping.Set(true, StatePlay, 0x09, PlayClientUpdateBlockEntity)
	mapping.Set(true, StatePlay, 0x0A, PlayClientBlockAction)
	mapping.Set(true, StatePlay, 0x0B, PlayClientBlockChange)
	mapping.Set(true, StatePlay, 0x0C, PlayClientBossBar)
	mapping.Set(true, StatePlay, 0x0D, PlayClientServerDifficulty)
	mapping.Set(true, StatePlay, 0x0E, PlayClientChatMessage)
	mapping.Set(true, StatePlay, 0x0F, PlayClientMultiBlockChange)

	mapping.Set(true, StatePlay, 0x10, PlayClientTabComplete)
	mapping.Set(true, StatePlay, 0x11, PlayClientDeclareCommands)
	mapping.Set(true, StatePlay, 0x12, PlayClientConfirmTransaction)
	mapping.Set(true, StatePlay, 0x13, PlayClientCloseWindow)
	mapping.Set(true, StatePlay, 0x14, PlayClientWindowItems)
	mapping.Set(true, StatePlay, 0x15, PlayClientWindowProperty)
	mapping.Set(true, StatePlay, 0x16, PlayClientSetSlot)
	mapping.Set(true, StatePlay, 0x17, PlayClientSetCooldown)
	mapping.Set(true, StatePlay, 0x18, PlayClientPluginMessage)
	mapping.Set(true, StatePlay, 0x19, PlayClientNamedSoundEffect)
	mapping.Set(true, StatePlay, 0x1A, PlayClientDisconnect)
	mapping.Set(true, StatePlay, 0x1B, PlayClientEntityStatus)
	mapping.Set(true, StatePlay, 0x1C, PlayClientExplosion)
	mapping.Set(true, StatePlay, 0x1D, PlayClientUnloadChunk)
	mapping.Set(true, StatePlay, 0x1E, PlayClientChangeGameState)
	mapping.Set(true, StatePlay, 0x1F, PlayClientOpenHorseWindow)

	mapping.Set(true, StatePlay, 0x20, PlayClientKeepAlive)
	mapping.Set(true, StatePlay, 0x21, PlayClientChunkData)
	mapping.Set(true, StatePlay, 0x22, PlayClientEffect)
	mapping.Set(true, StatePlay, 0x23, PlayClientParticle)
	mapping.Set(true, StatePlay, 0x24, PlayClientUpdateLight)
	mapping.Set(true, StatePlay, 0x25, PlayClientJoinGame)
	mapping.Set(true, StatePlay, 0x26, PlayClientMapData)
	mapping.Set(true, StatePlay, 0x27, PlayClientTradeList)
	mapping.Set(true, StatePlay, 0x28, PlayClientEntityRelativeMove)
	mapping.Set(true, StatePlay, 0x29, PlayClientEntityLookAndRelativeMove)
	mapping.Set(true, StatePlay, 0x2A, PlayClientEntityLook)
	mapping.Set(true, StatePlay, 0x2B, PlayClientEntity)
	mapping.Set(true, StatePlay, 0x2C, PlayClientVehicleMove)
	mapping.Set(true, StatePlay, 0x2D, PlayClientOpenBook)
	mapping.Set(true, StatePlay, 0x2E, PlayClientOpenWindow)
	mapping.Set(true, StatePlay, 0x2F, PlayClientOpenSignEditor)

	mapping.Set(true, StatePlay, 0x30, PlayClientCraftRecipeResponse)
	mapping.Set(true, StatePlay, 0x31, PlayClientPlayerAbilities)
	mapping.Set(true, StatePlay, 0x32, PlayClientCombatEvent)
	mapping.Set(true, StatePlay, 0x33, PlayClientPlayerInfo)
	mapping.Set(true, StatePlay, 0x34, PlayClientFacePlayer)
	mapping.Set(true, StatePlay, 0x35, PlayClientPlayerPositionAndLook)
	// mapping.Set(true, StatePlay, 0x33, PlayClientUseBed)
	mapping.Set(true, StatePlay, 0x36, PlayClientUnlockRecipes)
	mapping.Set(true, StatePlay, 0x37, PlayClientDestroyEntities)
	mapping.Set(true, StatePlay, 0x38, PlayClientRemoveEntityEffect)
	mapping.Set(true, StatePlay, 0x39, PlayClientResourcePackSend)
	mapping.Set(true, StatePlay, 0x3A, PlayClientRespawn)
	mapping.Set(true, StatePlay, 0x3B, PlayClientEntityHeadLook)
	mapping.Set(true, StatePlay, 0x3C, PlayClientSelectAdvancementTab)
	mapping.Set(true, StatePlay, 0x3D, PlayClientWorldBorder)
	mapping.Set(true, StatePlay, 0x3E, PlayClientCamera)
	mapping.Set(true, StatePlay, 0x3F, PlayClientHeldItemChange)

	mapping.Set(true, StatePlay, 0x40, PlayClientUpdateViewPosition)
	mapping.Set(true, StatePlay, 0x41, PlayClientUpdateViewDistance)
	mapping.Set(true, StatePlay, 0x42, PlayClientDisplayScoreboard)
	mapping.Set(true, StatePlay, 0x43, PlayClientEntityMetadata)
	mapping.Set(true, StatePlay, 0x44, PlayClientAttachEntity)
	mapping.Set(true, StatePlay, 0x45, PlayClientEntityVelocity)
	mapping.Set(true, StatePlay, 0x46, PlayClientEntityEquipment)
	mapping.Set(true, StatePlay, 0x47, PlayClientSetExperience)
	mapping.Set(true, StatePlay, 0x48, PlayClientUpdateHealth)
	mapping.Set(true, StatePlay, 0x49, PlayClientScoreboardObjective)
	mapping.Set(true, StatePlay, 0x4A, PlayClientSetPassengers)
	mapping.Set(true, StatePlay, 0x4B, PlayClientTeams)
	mapping.Set(true, StatePlay, 0x4C, PlayClientUpdateScore)
	mapping.Set(true, StatePlay, 0x4D, PlayClientSpawnPosition)
	mapping.Set(true, StatePlay, 0x4E, PlayClientTimeUpdate)
	mapping.Set(true, StatePlay, 0x4F, PlayClientTitle)

	mapping.Set(true, StatePlay, 0x50, PlayClientEntitySoundEffect)
	mapping.Set(true, StatePlay, 0x51, PlayClientSoundEffect)
	mapping.Set(true, StatePlay, 0x52, PlayClientStopSound)
	mapping.Set(true, StatePlay, 0x53, PlayClientPlayerListHeaderAndFooter)
	mapping.Set(true, StatePlay, 0x54, PlayClientNBTQueryResponse)
	mapping.Set(true, StatePlay, 0x55, PlayClientCollectItem)
	mapping.Set(true, StatePlay, 0x56, PlayClientEntityTeleport)
	mapping.Set(true, StatePlay, 0x57, PlayClientAdvancements)
	mapping.Set(true, StatePlay, 0x58, PlayClientEntityProperties)
	mapping.Set(true, StatePlay, 0x59, PlayClientEntityEffect)
	mapping.Set(true, StatePlay, 0x5A, PlayClientDeclareRecipes)
	mapping.Set(true, StatePlay, 0x5B, PlayClientTags)

	// serverbound
	mapping.Set(false, StatePlay, 0x00, PlayServerTeleportConfirm)
	mapping.Set(false, StatePlay, 0x01, PlayServerQueryBlockNBT)
	mapping.Set(false, StatePlay, 0x02, PlayServerSetDifficulty)
	mapping.Set(false, StatePlay, 0x03, PlayServerChatMessage)
	mapping.Set(false, StatePlay, 0x04, PlayServerClientStatus)
	mapping.Set(false, StatePlay, 0x05, PlayServerClientSettings)
	mapping.Set(false, StatePlay, 0x06, PlayServerTabComplete)
	mapping.Set(false, StatePlay, 0x07, PlayServerConfirmTransaction)
	mapping.Set(false, StatePlay, 0x08, PlayServerClickWindowButton)
	mapping.Set(false, StatePlay, 0x09, PlayServerClickWindow)
	mapping.Set(false, StatePlay, 0x0A, PlayServerCloseWindow)
	mapping.Set(false, StatePlay, 0x0B, PlayServerPluginMessage)
	mapping.Set(false, StatePlay, 0x0C, PlayServerEditBook)
	mapping.Set(false, StatePlay, 0x0D, PlayServerQueryEntityNBT)
	mapping.Set(false, StatePlay, 0x0E, PlayServerUseEntity)
	mapping.Set(false, StatePlay, 0x0F, PlayServerKeepAlive)

	// mapping.Set(false, StatePlay, 0x17, PlayServerEnchantItem)

	mapping.Set(false, StatePlay, 0x10, PlayServerLockDifficulty)
	mapping.Set(false, StatePlay, 0x11, PlayServerPlayerPosition)
	mapping.Set(false, StatePlay, 0x12, PlayServerPlayerPositionAndLook)
	mapping.Set(false, StatePlay, 0x13, PlayServerPlayerLook)
	mapping.Set(false, StatePlay, 0x14, PlayServerPlayer)
	mapping.Set(false, StatePlay, 0x15, PlayServerVehicleMove)
	mapping.Set(false, StatePlay, 0x16, PlayServerSteerBoat)
	mapping.Set(false, StatePlay, 0x17, PlayServerPickItem)
	mapping.Set(false, StatePlay, 0x18, PlayServerCraftRecipeRequest)
	mapping.Set(false, StatePlay, 0x19, PlayServerPlayerAbilities)
	mapping.Set(false, StatePlay, 0x1A, PlayServerPlayerDigging)
	mapping.Set(false, StatePlay, 0x1B, PlayServerEntityAction)
	mapping.Set(false, StatePlay, 0x1C, PlayServerSteerVehicle)
	mapping.Set(false, StatePlay, 0x1D, PlayServerRecipeBookData)
	mapping.Set(false, StatePlay, 0x1E, PlayServerNameItem)
	mapping.Set(false, StatePlay, 0x1F, PlayServerResourcePackStatus)

	mapping.Set(false, StatePlay, 0x20, PlayServerAdvancementTab)
	mapping.Set(false, StatePlay, 0x21, PlayServerSelectTrade)
	mapping.Set(false, StatePlay, 0x22, PlayServerSetBeaconEffect)
	mapping.Set(false, StatePlay, 0x23, PlayServerHeldItemChange)
	mapping.Set(false, StatePlay, 0x24, PlayServerUpdateCommandBlock)
	mapping.Set(false, StatePlay, 0x25, PlayServerUpdateCommandBlockMinecart)
	mapping.Set(false, StatePlay, 0x26, PlayServerCreativeInventoryAction)
	mapping.Set(false, StatePlay, 0x27, PlayServerUpdateJigsawBlock)
	mapping.Set(false, StatePlay, 0x28, PlayServerUpdateStructureBlock)
	mapping.Set(false, StatePlay, 0x29, PlayServerUpdateSign)
	mapping.Set(false, StatePlay, 0x2A, PlayServerAnimation)
	mapping.Set(false, StatePlay, 0x2B, PlayServerSpectate)
	mapping.Set(false, StatePlay, 0x2C, PlayServerPlayerBlockPlacement)
	mapping.Set(false, StatePlay, 0x2D, PlayServerUseItem)

	mapping.finish(482)
}
